services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bluequest
      MYSQL_USER: bluequest
      MYSQL_PASSWORD: bluequest
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql


  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: ["redis-server", "--save", "", "--appendonly", "no"]


  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data


  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '8025:8025'
      - '1025:1025'


volumes:
  mysql_data:
  minio_data: