services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bluequest
      MYSQL_USER: bluequest
      MYSQL_PASSWORD: bluequest
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: